# Generated by Django 4.0 on 2022-01-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
